plugin: gcp_compute
zones: # populate inventory with instances in these regions
  - europe-west1-b
projects:
  - infra-262619
service_account_file: ~/.gsutil/infra-262619-c9ac92f00766.json
auth_kind: serviceaccount
scopes:
 - 'https://www.googleapis.com/auth/cloud-platform'
 - 'https://www.googleapis.com/auth/compute.readonly'
groups:
  app: "'-app' in name"
  db: "'-db' in name"
filters: []
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
